version: '3.4'

services:
  clientapp:
    image: ${DOCKER_REGISTRY-}clientapp
    build:
      context: .
      dockerfile: ClientApp/Dockerfile

  myappdb:
    container_name: MyAppDB
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "My_Pass12"
      ACCEPT_EULA: "Y"
      
  myapp:
    depends_on:
      - myappdb
    image: ${DOCKER_REGISTRY-}myapp
    build:
      context: .
      dockerfile: MyApp/Dockerfile

  contentappdb:
    container_name: ContentAppDB
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "My_Pass12"
      ACCEPT_EULA: "Y"

  contentapp:
    depends_on:
      - myappdb
      - contentappdb
    image: ${DOCKER_REGISTRY-}contentapp
    build:
      context: .
      dockerfile: ContentApp/Dockerfile

  rabbitmq:
    container_name: Rabbit
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "RabbitMQ"
    ports:
    - "5672:5672"
    - "15672:15672"